name: lgm

services:
  hugo:
    image: ghcr.io/gohugoio/hugo:v0.149.1
    entrypoint: hugo
    command: server --bind 0.0.0.0 --renderToMemory
    ports:
      - "127.0.0.1:1313:1313"
    volumes:
      - .:/project
