backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Catégorie", name: "category", widget: "select", options: ["paris-ispahan","tour-des-zagoria","autre"] }
      - { label: "Corps de l'article", name: "body", widget: "markdown" }
